# Generated by Django 6.0.2 on 2026-02-15 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category name')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FullQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('system_answer', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='guessing_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuizToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guessing_app.fullquiz')),
            ],
        ),
    ]
