# Generated by Django 6.0.2 on 2026-02-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
