# Generated by Django 6.0.2 on 2026-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0002_rename_category_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztouser',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiztouser',
            name='user_answer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
