# Generated by Django 6.0.2 on 2026-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0003_alter_quiztouser_score_alter_quiztouser_user_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizToUser',
            new_name='QuizAnswer',
        ),
    ]
