# Generated by Django 6.0.2 on 2026-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0004_rename_quiztouser_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='user_answer',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
