# Generated by Django 6.0.2 on 2026-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0005_alter_quizanswer_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
