# Generated by Django 6.0.2 on 2026-02-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0006_alter_quizanswer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guessing_app.fullquiz'),
        ),
    ]
