# Generated by Django 6.0.2 on 2026-02-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0007_alter_quizanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guessing_app.fullquiz'),
        ),
    ]
