# Generated by Django 6.0.2 on 2026-02-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0008_alter_quizanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='id',
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guessing_app.fullquiz'),
        ),
    ]
