# Generated by Django 6.0.2 on 2026-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0009_remove_quizanswer_id_alter_quizanswer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
