# Generated by Django 6.0.2 on 2026-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0010_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
