# Generated by Django 6.0.2 on 2026-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_app', '0011_history_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
